### ISSUE TITLE
eslint.Linter is not a constructor TypeError: eslint.Linter is not a constructor

### ISSUE THREAD

**Issue by ashokrse2020** [babel/eslint-plugin-babel#140]
git:(release-1.5.2) ✗ ./node_modules/.bin/eslint --fix src
eslint.Linter is not a constructor
TypeError: eslint.Linter is not a constructor
    at Object.<anonymous> (/Users/ashokr/Projects/Tekion/Mobile/tekion_cdms_mobile/node_modules/eslint-plugin-babel/rules/new-cap.js:5:20)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/ashokr/Projects/Tekion/Mobile/tekion_cdms_mobile/node_modules/eslint-plugin-babel/index.js:10:16)
    at Module._compile (module.js:624:30)

**Comment by existentialism** [comment]
@AshokICreate what version of ESLint are you using?

**Comment by AshokICreate** [comment]
eslint --version
v4.10.0

**Comment by DaveStein** [comment]
I am getting this in 5.0.0

**Comment by DaveStein** [comment]
I was getting this after updating `eslint-plugin-babel` without updating `eslint`. After that, I had separate issues because it turned out the repo I was in was on 3* vs 4*.

**Comment by suchipi** [comment]
@younesmln nope, but if you are experiencing it, if you could create a small repro repo we can clone and run a couple commands in to see the bug, that would help us diagnose the issue.

**Comment by luisaccedo** [comment]
+1

**Comment by Yurajun** [comment]
I deleted the babel plugin from the list of plugins in the eslintrc file and the error disappeared. Now everything is working stably.

**Comment by ErikBoesen** [comment]
@suchipi I am having this issue and am happy to create a repro repo for you if you still want it.

**Comment by existentialism** [comment]
@ErikBoesen please do!

**Comment by DaveStein** [comment]
> I was getting this after updating `eslint-plugin-babel` without updating `eslint`. After that, I had separate issues because it turned out the repo I was in was on 3* vs 4*.

PS, since I got a thumbs down: was just calling out a silly mistake that someone else might do that would hit this issue

**Comment by asolopovas** [comment]
Similar error pops out in PhpStorm
```
TypeError: this.cliEngine is not a constructor

TypeError: this.cliEngine is not a constructor
    at ESLintPlugin.invokeESLint (C:\Program Files\JetBrains\PhpStorm\plugins\JavaScriptLanguage\languageService\eslint\bin\eslint-plugin.js:97:25)
    at ESLintPlugin.getErrors (C:\Program Files\JetBrains\PhpStorm\plugins\JavaScriptLanguage\languageService\eslint\bin\eslint-plugin.js:76:21)
    at ESLintPlugin.onMessage (C:\Program Files\JetBrains\PhpStorm\plugins\JavaScriptLanguage\languageService\eslint\bin\eslint-plugin.js:42:29)
    at Interface.<anonymous> (C:\Program Files\JetBrains\PhpStorm\plugins\JavaScriptLanguage\jsLanguageServicesImpl\js-language-service.js:105:39)
    at Interface.emit (events.js:182:13)
    at Interface._onLine (readline.js:290:10)
    at Interface._normalWrite (readline.js:433:12)
    at Socket.ondata (readline.js:149:10)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:283:12)
```

**Comment by fiftystorm36** [comment]
If you use JetBrains IDE, apply 2019.1.3 patch.

https://intellij-support.jetbrains.com/hc/en-us/community/posts/360004195120-TypeError-this-cliEngine-is-not-a-constructor

**Comment by kaicataldo** [comment]
Thank you for the issue. Now that [@babel/eslint-plugin has been released](https://babeljs.io/blog/2020/07/13/the-state-of-babel-eslint), we are making this repository read-only. If this is a change you would still like to advocate for, please reopen this in the [babel/babel monorepo](https://github.com/babel/babel).
